version: "3.9"
services:

  database:
    container_name: kupipodariday_db
    image: "postgres:12.13-alpine"
    env_file: .env
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - kupipodariday-db
    restart: on-failure

  backend:
    container_name: kupipodariday_backend
    build: ./backend
    env_file: .env
    ports:
      - "4000:3001"
    networks:
      - kupipodariday-backend
      - kupipodariday-db
    depends_on:
      - database
    healthcheck:
      test: "wget -nv -t1 --spider 'http://localhost:3001/'"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure

  frontend:
    container_name: kupipodariday_frontend
    build: ./frontend
    ports:
      - "8081:80"
    networks:
      - kupipodariday-backend
    depends_on:
      - backend
    restart: on-failure


networks:
  kupipodariday-db: 
    driver: bridge
    internal: true
  kupipodariday-backend:
    driver: bridge